### PR TITLE
Correct TRPC error handling to be on par with existing REST error handling

### LINKED ISSUE #258: Correct TRPC error handling to be on par with existing REST error handling
Noticed some issues with errors that occur in backend of TRPC

Had some code failing in backend (always a possibility) - and that correctly errored out the TRCP mutation..

However - nothing was logged in the backend - where I would expect at the minimum all errors in "services" are trapped/logged and passed through.. (not by adding catch clauses, by using the fastify/trcp hooks)

*Also* TRPC has a completely custom error code mechanism. Need to think if instead we want to translate these to the RFC7807 error format that we are using for our regular REST apis (it is possible to do error shapes in TRPC so I think this would be relatively straightforward - though possibly not bother?)

### PR DESCRIPTION
**Pull request by DoxasticFox**
I couldn't find a way to propagate the `Base7807Error`s to the frontend and neither could ChatGPT :'(

tRPC still propagates the `Error`'s `message` property to the frontend, which is better than nothing, but the type is changed and things like `title`, `status`, and `detail` are missing. The `onError` callback in this PR still has access to the original server-side exception (burred in the `error.error.cause`) though, so at least it can be logged to the console.

Closes https://github.com/umccr/elsa-data/issues/258

### CODE REVIEW

File: application/backend/src/api/api-trpc-routes.ts [hunk 1]
```diff
@@ -26,6 +26,9 @@ export const trpcRoutes = async (
     trpcOptions: {
       router: appRouter,
       createContext: opts.trpcCreateContext,
+      onError: (error: any) => {
```
Comment (andrewpatto) [inline application/backend/src/api/api-trpc-routes.ts]: is there a TRPC error type? (given the assumption of a .error.cause in the next line?)

**Review by andrewpatto — APPROVED** [review]

**Comment by andrewpatto** [comment]
Can you add to the EagerErrorBoundary (and related) React components so that they detect when the error is a TRPC v 7807 and correctly find/display the relevant fields?

**Comment by DoxasticFox** [comment]
>Can you add to the EagerErrorBoundary (and related) React components so that they detect when the error is a TRPC v 7807 and correctly find/display the relevant fields?

I just pushed this change, but the only extra field I added is the `code` (aka `httpStatus`). To give you a sense for what's revealed to the client, here's what `JSON.stringify(activateMutation.error ?? deactivateMutation.error)` contains when the server raises a `ReleaseActivationStateError`:

```json
{
  "meta": {
    "response": {}
  },
  "shape": {
    "message": "An attempt was made to activate a release that was already activated",
    "code": -32603,
    "data": {
      "code": "INTERNAL_SERVER_ERROR",
      "httpStatus": 500,
      "stack": "ReleaseActivationStateError: An attempt was made to activate a release that was already activated\n    at ReleaseActivationService.activateRelease (/home/christian/elsa-data/application/backend/src/business/services/release-activation-service.ts:46:11)\n    at /home/christian/elsa-data/application/backend/src/api/routes/internal-trpc/release-activation-router.ts:12:42\n    at resolveMiddleware (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:418:36)\n    at callRecursive (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:38)\n    at next (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:462:38)\n    at inputMiddleware (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:288:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async callRecursive (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:32)\n    at async next (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:462:32)\n    at async callRecursive (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:32)",
      "path": "releaseActivation.activate"
    }
  },
  "data": {
    "code": "INTERNAL_SERVER_ERROR",
    "httpStatus": 500,
    "stack": "ReleaseActivationStateError: An attempt was made to activate a release that was already activated\n    at ReleaseActivationService.activateRelease (/home/christian/elsa-data/application/backend/src/business/services/release-activation-service.ts:46:11)\n    at /home/christian/elsa-data/application/backend/src/api/routes/internal-trpc/release-activation-router.ts:12:42\n    at resolveMiddleware (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:418:36)\n    at callRecursive (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:38)\n    at next (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:462:38)\n    at inputMiddleware (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:288:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async callRecursive (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:32)\n    at async next (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:462:32)\n    at async callRecursive (/home/christian/elsa-data/application/backend/node_modules/@trpc/server/dist/index.js:454:32)",
    "path": "releaseActivation.activate"
  },
  "name": "TRPCClientError"
}
```

**Comment by williamputraintan** [comment]
Sorry for late comment here, but I think we could still pass the title, status, and detail through an errorFormatter (described [here](https://trpc.io/docs/server/error-formatting#all-properties-sent-to-errorformatter)). 

I managed to try it out so possibly we will have something like this on the [`trpc-bootstrap.ts`](https://github.com/umccr/elsa-data/blob/e3369bc0e84c154b4e3c909da37903ed079a448e/application/backend/src/api/routes/trpc-bootstrap.ts#L31):

```
const t = initTRPC.context<Context>().create({
  errorFormatter({ shape, error }) {
    return {
      ...shape,
      data: {
        ...error.cause,
      },
    };
  },
});
```

and on the FE `mutation.error` it will become 

```
{
  "meta": {
    "response": {}
  },
  "shape": {
    "message": "An attempt was made to activate a release that was already activated",
    "code": -32603,
    "data": {
      "status": 400,
      "detail": "The release with id 'R001' is activated and hence cannot be activated again",
      "name": "ReleaseActivationStateError",
      "message": "An attempt was made to activate a release that was already activated"
    }
  },
  "data": {
    "status": 400,
    "detail": "The release with id 'R001' is activated and hence cannot be activated again",
    "name": "ReleaseActivationStateError",
    "message": "An attempt was made to activate a release that was already activated"
  },
  "name": "TRPCClientError"
}
```

Although the status network call still return `500` despite the error itself is a `400` status code. 

Manage to try ```throw opts.error.cause;``` on the trpc `onError` options (on the `trpcOptions`) which then return the correct API status code and data but TRPC client Error do not contain data return above.

**Comment by williamputraintan** [comment]
I'm happy to make the change if this a better solution?

**Comment by DoxasticFox** [comment]
@williamputraintan Yes! This is the kind of thing I wanted!
