### PR TITLE
refactor(frontend): fix numerous details and UI elements

### LINKED ISSUE #338: UI issues on user page
Screenshot 2023-05-17 at 9 14 08 am

- [ ] top align the list of permissions
- [ ] table should be more like our other tables - column headers, styling as per release table (dasiy where possible), page box at bottom
- [ ] rather than a edit icon - should use the word "edit" as a link button on the right (same as releases table)

### PR DESCRIPTION
**Pull request by mmalenic**
Closes #338 

### Changes
* Users page:
    * Change edit icon to word.
    * Move edit icon from basic info.
    * Put paginator on bottom.
    * Reorder columns.
    * Fix gap between permissions heading and the list of permissions.
* Change colours of top-level navigation to the DaisyUI primary theme.
* Style more checkboxes with DaisyUI.
* Vertical tabs use DaisyUI theme.

### Users page
image

### CODE REVIEW

File: application/frontend/src/pages/releases/detail/information-box.tsx [hunk 1]
```diff
@@ -112,22 +112,6 @@ export const InformationBox: React.FC<Props> = ({
           </div>
         )}
 
-        <div className="collapse-arrow rounded-box collapse col-span-2 border border-base-300 bg-base-100">
```
Comment (mmalenic) [inline application/frontend/src/pages/releases/detail/information-box.tsx:115]: I'm not sure if this was doing anything. Should we remove it, or should the details be optionally enabled with a checkbox?

File: application/frontend/src/pages/releases/detail/information-box.tsx [hunk 2]
```diff
@@ -112,22 +112,6 @@ export const InformationBox: React.FC<Props> = ({
...
-          <div className="collapse-content">
-            {releaseData.applicationDacDetails && (
-              <ReactMarkdown
-                remarkPlugins={[remarkGfm]}
-                className="prose"
-                children={releaseData.applicationDacDetails}
-              />
-            )}
-          </div>
-        </div>
```
Comment (mmalenic) [inline application/frontend/src/pages/releases/detail/information-box.tsx]: I'm not sure if this was doing anything. Should we remove it, or should the details be optionally enabled with a checkbox?

Comment (andrewpatto) [reply application/frontend/src/pages/releases/detail/information-box.tsx]: Yeah - when you click on the collapse item it then instead displays the entire text of the application (for real applicaitons this might be lots of text about the study aims etc)

Comment (andrewpatto) [reply application/frontend/src/pages/releases/detail/information-box.tsx]: Happy to use an alternative daisy friendly mechanism

**Comment by andrewpatto** [comment]
The text in the table (non headers) looks heavy (i.e. bold).. are they done at `th` rather than `td`?

**Review by andrewpatto — APPROVED** [review]

**Comment by mmalenic** [comment]
> The text in the table (non headers) looks heavy (i.e. bold).. are they done at `th` rather than `td`?

Ahh yes, I will unbold it. It is using td though.

File: application/frontend/src/pages/users-dashboard/other-users/other-users.tsx [hunk 3]
```diff
@@ -90,21 +90,27 @@ export const OtherUsers: React.FC<Props> = ({ pageSize }) => {
...
+          Permissions
+        </th>
+      </tr>
+    );
+  };
+
   const createRows = (data: UserSummaryType[]) => {
     return data.map((row, rowIndex) => {
       return (
         <tr key={rowIndex} className="border-b pl-2 pr-2">
```
Comment (andrewpatto) [inline application/frontend/src/pages/users-dashboard/other-users/other-users.tsx:113]: do we have these classes on other daisy table rows? If not can we remove and leave it as default daisy as possible
(will then be more themable if we change the daisy settings themselves)

Comment (mmalenic) [reply application/frontend/src/pages/users-dashboard/other-users/other-users.tsx:113]: No, that's a good idea.

**Comment by mmalenic** [comment]
Update: allow pressing the edit button even though the user cannot make changes - as the permission box already handles this.
